# Use root/example as user/password credentials
version: '3.8'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - ./docker/mongo/data:/data/db # https://betterprogramming.pub/persistent-databases-using-dockers-volumes-and-mongodb-9ac284c25b39